name: t2dc
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - filelock=3.13.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - jinja2=3.1.2
  - libcxx=14.0.6
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - llvm-openmp=14.0.6
  - markupsafe=2.1.1
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.1
  - numexpr=2.8.7
  - numpy-base=1.26.0
  - openssl=3.0.12
  - pandas=2.1.1
  - pip=23.3.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytorch=2.1.1
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tk=8.6.12
  - typing_extensions=4.7.1
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - fsspec==2023.10.0
      - huggingface-hub==0.19.4
      - idna==3.6
      - joblib==1.3.2
      - numpy==1.26.2
      - packaging==23.2
      - regex==2023.10.3
      - requests==2.31.0
      - safetensors==0.4.1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - threadpoolctl==3.2.0
      - tokenizers==0.15.0
      - tqdm==4.66.1
      - transformers==4.35.2
      - typing-extensions==4.8.0
      - urllib3==2.1.0
